/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_fzi_ekgeditor_analysis_Osea4Msp */

#ifndef _Included_de_fzi_ekgeditor_analysis_Osea4Msp
#define _Included_de_fzi_ekgeditor_analysis_Osea4Msp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_fzi_ekgeditor_analysis_Osea4Msp
 * Method:    analyze
 * Signature: ([SI)[I
 */
JNIEXPORT jintArray JNICALL Java_de_fzi_ekgeditor_analysis_Osea4Msp_analyze
  (JNIEnv *, jobject, jshortArray, jint);

/*
 * Class:     de_fzi_ekgeditor_analysis_Osea4Msp
 * Method:    getCurrentSample
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_fzi_ekgeditor_analysis_Osea4Msp_getCurrentSample
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
