/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_fzi_ekgeditor_algorithm_jni_OseaQrsDet2AlgorithmJNI */

#ifndef _Included_de_fzi_ekgeditor_algorithm_jni_OseaQrsDet2AlgorithmJNI
#define _Included_de_fzi_ekgeditor_algorithm_jni_OseaQrsDet2AlgorithmJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_fzi_ekgeditor_algorithm_jni_OseaQrsDet2AlgorithmJNI
 * Method:    initJNI
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_de_fzi_ekgeditor_algorithm_jni_OseaQrsDet2AlgorithmJNI_initJNI
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     de_fzi_ekgeditor_algorithm_jni_OseaQrsDet2AlgorithmJNI
 * Method:    process
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_de_fzi_ekgeditor_algorithm_jni_OseaQrsDet2AlgorithmJNI_process
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
